### PR TITLE
resolves #73 TCPConnection can reconnect even if the TCP server wasn't available at first

### LINKED ISSUE #73: Logs are not sent if the TCP server wasn't available when the logger was initialized
It seems that `pino-socket` can reconnect to a TCP server (using the `reconnect` option) but if the TCP server wasn't available when the logger (multistream?) was initialized then the server won't receive any data.

I've created a simple reproduction case because it's hard to explain but relatively straightforward to reproduce: https://github.com/Mogztter/pino-socket-reconnect

My observations:
- `pino-socket` successfully reconnect (connect) to the TCP server and stops sending `connect ECONNREFUSED 127.0.0.1:13370` as soon as the server is started
- `stream.write(data)` in `multistream` is called
- `ThreadStream.write` is called but `writeSync` is not, we keep calling `nextFlush`
- the `write` function defined on the `outputStream` in `TcpConnection` is not called

Hopefully, I didn't miss something obvious 😅

### PR DESCRIPTION
**Pull request by Mogztter**

### CODE REVIEW

File: test/tcpReconnect.js [hunk 1]
```diff
@@ -85,3 +88,48 @@ test('tcp reconnect', function testTcpReconnect (done) {
...
+              received.push(msg)
+              if (!closing) {
+                closing = true
+                server.close(() => {
+                  resolve(received)
+                })
+              }
+          }
+        }
+      })
```
Comment (mcollina) [inline test/tcpReconnect.js:129]: Avoid using timers but instead use logical events.

**Review by mcollina — CHANGES_REQUESTED** [review]

File: test/tcpReconnect.js (hunk 1 above)
Comment (Mogztter) [reply test/tcpReconnect.js]: I've removed the timer since we don't need it. When we instantiate `TcpConnection` it will try to connect and fail because the server has not yet started (i.e., we don't need to wait for `tcpConnection.write`).

**Comment by mcollina** [comment]
This new test seems passing without any code changes, is that expected?

**Comment by Mogztter** [comment]
> This new test seems passing without any code changes, is that expected?

Yes, the `TCPConnection` can reconnect even if `open` is not emitted. However, ThreadStream will not write/send data to the stream if `open` is not emitted.

In https://github.com/pinojs/pino-socket/pull/78 I make sure that the `open` event is emitted (to honor ThreadStream contract)
